@startuml
'https://plantuml.com/activity-diagram-beta

start
    :MainActivity;
    :LoginActivity;
    if () then ( cadastrar() )
        :CadastrarActivity;
    else ( login() )
        :ListaActivity();
        if ( lista.itemClick() )
          :ListadeCompras;
          if ( btnAddItem() ) then
            :CadastrarItemActivity;
            endif
        endif
stop

@enduml
